import Head from 'next/head'
import { REACT_APP_CLIENT_ID, REACT_APP_AUTHORIZE_URL, REACT_APP_REDIRECT_URL } from "../lib/spotify"

import styles from '../styles/Home.module.css'

export default function Home() {

  const handleLogin = () => {
    window.location = `${REACT_APP_AUTHORIZE_URL}?client_id=${REACT_APP_CLIENT_ID}&redirect_uri=${REACT_APP_REDIRECT_URL}&response_type=token&show_dialog=true` 
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Music Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.title}>
          <h1><strong>Spotify</strong> Login</h1>
          <p>Nossos servições são integrados com os serviços do Spotify, por favor faça o login para continuar.</p>
        </div>
        <button onClick={handleLogin}>Login</button>
      </main>

      <footer className={styles.footer}>
        Feito com 💙 por Bruno Coutinho
      </footer>
    </div>
  )
}
