import { useRouter } from 'next/router'
import Head from 'next/head'
import { FaSearch } from "react-icons/fa"
import { useState } from 'react'
import styles from '../styles/Redirect.module.css'

export default function Redirect() {

  const [searchTerm, setSearchTerm] = useState('')
  const [artistsList, setArtistsList] = useState([])
  const [albumList, setAlbumList] = useState([])
  const [playlistList, setPlaylistList] = useState([])
  const [imagesList, setImagesList] = useState([])

  const getToken = () => { 
    var hashParams = {};
    var e, r = /([^&;=]+)=?([^&;]*)/g,
    q = window.location.hash.substring(1);
    e = r.exec(q)
    while (e) {
    hashParams[e[1]] = decodeURIComponent(e[2]);
    e = r.exec(q);
    }
    return(hashParams)
  }

  const handleSearch = async () => {

    const params = getToken()
    const token = params.access_token

    const response = await fetch(`https://api.spotify.com/v1/search?query=${searchTerm}&type=album,playlist,artist`, {
      headers: {
        Authorization: `Bearer ${token}`
      }
    })
    const json = await response.json()
    console.log(json.artists.items)
    setArtistsList(json.artists.items)
    setAlbumList(json.albums.items)
    setPlaylistList(json.playlists.items)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Music Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem vindo(a) ao <strong>Music Finder</strong>
        </h1>
        <div className={styles.input_container}>
          <input type="text" placeholder="Artistas, músicas ou podcast" onChange={e=> setSearchTerm(e.target.value)} value={searchTerm}/>
          <button onClick={handleSearch}><FaSearch /></button>
        </div>

        <div className={styles.artist_container}>
        {artistsList.map((artist, key)=>(
            <div className={styles.artist} key={key}>
              <img src={artist.images.url}/>
              <h1>{artist.name}</h1>
            </div>
          ))}
        </div>

        <div className={styles.album_container}>
        {albumList.map(album=>(
            <div className={styles.album}>
              <h1>{album.name}</h1>
            </div>
          ))}
        </div>

        <div className={styles.playlist_container}>
        {playlistList.map(playlist=>(
            <div className={styles.playlist}>
              <h1>{playlist.name}</h1>
            </div>
          ))}
        </div>
        
      </main>

      <footer className={styles.footer}>
        Feito com 💙 por Bruno Coutinho
      </footer>
    </div>
  )
}